# Flujo de datos con Python

Alan Badillo Salas

> Belatrix, lunes 18, mayo 2026.

In [9]:
! python -V

Python 3.14.2

In [10]:
! python -m pip install numpy pandas matplotlib seaborn scikit-learn

Requirement already satisfied: numpy in e:\python314\lib\site-packages (2.4.5)
Requirement already satisfied: pandas in e:\python314\lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in e:\python314\lib\site-packages (3.10.9)
Requirement already satisfied: seaborn in e:\python314\lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in e:\python314\lib\site-packages (1.8.0)
Requirement already satisfied: python-dateutil>=2.8.2 in e:\python314\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in e:\python314\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in e:\python314\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in e:\python314\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in e:\python314\lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in e:\python314\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in e:\python314\lib\site-packages (from matplotlib) (26.2)
Requirement already satisfied: pillow>=8 in e:\python314\lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in e:\python314\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in e:\python314\lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in e:\python314\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in e:\python314\lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in e:\python314\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Paso 1 - Cargar los datos CSV de la financiera

In [11]:
import pandas

financiera = pandas.read_csv("financiera.csv")

financiera

,folio,amortizacionId,numero,concepto,plan,plazos,precio,interes,anticipo,subtotal,...,pagoMontoFaltante,pagoAnteriorId,pagoSiguienteId,vendedorRecibeFolio,sucursalRecibeFolio,vendedorOrigenFolio,sucursalOrigenFolio,liquidado,amortizacionAnteriorId,amortizacionSiguienteId
0,772,anticipo,0,Anticipo,nuevo,26,3999.0,190.0,799.0,6080.0,...,0.00,NaN,pago-1,33.0,6.0,12.0,14.0,0,NaN,pago-1
1,772,pago-1,1,Pago 1 de 26,nuevo,26,3999.0,190.0,799.0,6080.0,...,233.85,anticipo,pago-2,NaN,NaN,NaN,NaN,0,anticipo,pago-2
2,772,pago-2,2,Pago 2 de 26,nuevo,26,3999.0,190.0,799.0,6080.0,...,233.85,pago-1,pago-3,NaN,NaN,NaN,NaN,0,pago-1,pago-3
3,772,pago-3,3,Pago 3 de 26,nuevo,26,3999.0,190.0,799.0,6080.0,...,233.85,pago-2,pago-4,NaN,NaN,NaN,NaN,0,pago-2,pago-4
4,772,pago-4,4,Pago 4 de 26,nuevo,26,3999.0,190.0,799.0,6080.0,...,233.85,pago-3,pago-5,NaN,NaN,NaN,NaN,0,pago-3,pago-5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13916,9,pago-14,14,Pago 14 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,0.00,pago-13,pago-15,18.0,11.0,14.0,11.0,0,pago-13,pago-15
13917,9,pago-15,15,Pago 15 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,0.00,pago-14,pago-16,14.0,11.0,14.0,11.0,0,pago-14,pago-16
13918,9,pago-16,16,Pago 16 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,0.00,pago-15,pago-17,18.0,11.0,14.0,11.0,0,pago-15,pago-17
13919,9,pago-17,17,Pago 17 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,0.00,pago-16,pago-18,18.0,11.0,14.0,11.0,0,pago-16,pago-18
13920,9,pago-18,18,Pago 18 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,0.00,pago-17,NaN,14.0,11.0,14.0,11.0,0,pago-17,NaN

In [12]:
financiera.info()

<class 'pandas.DataFrame'>
RangeIndex: 13921 entries, 0 to 13920
Data columns (total 39 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   folio                           13921 non-null  int64
 1   amortizacionId                  13921 non-null  str
 2   numero                          13921 non-null  int64
 3   concepto                        13921 non-null  str
 4   plan                            13921 non-null  str
 5   plazos                          13921 non-null  int64
 6   precio                          13921 non-null  float64
 7   interes                         13921 non-null  float64
 8   anticipo                        13921 non-null  float64
 9   subtotal                        13921 non-null  float64
 10  semanal                         13921 non-null  float64
 11  total                           13921 non-null  float64
 12  saldoTotal                      13921 non-null  float64
 13  saldoActual                     13921 non-null  float64
 14  totalPagado                     13921 non-null  float64
 15  liquidacion                     13921 non-null  float64
 16  pagado                          13921 non-null  int64
 17  pagoNumero                      7977 non-null   float64
 18  pagoPlazo                       13921 non-null  int64
 19  pagoFechaEsperada               13921 non-null  str
 20  pagoFechaRecibido               7986 non-null   str
 21  pagoMontoEsperado               13921 non-null  float64
 22  pagoMontoRecibidoEfectivo       13921 non-null  float64
 23  pagoMontoRecibidoTarjeta        13921 non-null  float64
 24  pagoMontoRecibidoTransferencia  13921 non-null  float64
 25  pagoMontoRecibidoAjustado       13921 non-null  float64
 26  pagoMontoRecibido               13921 non-null  float64
 27  pagoMontoAportado               13921 non-null  float64
 28  pagoMontoExcedente              13921 non-null  float64
 29  pagoMontoFaltante               13921 non-null  float64
 30  pagoAnteriorId                  13477 non-null  str
 31  pagoSiguienteId                 13477 non-null  str
 32  vendedorRecibeFolio             7873 non-null   float64
 33  sucursalRecibeFolio             7977 non-null   float64
 34  vendedorOrigenFolio             7977 non-null   float64
 35  sucursalOrigenFolio             7977 non-null   float64
 36  liquidado                       13921 non-null  int64
 37  amortizacionAnteriorId          13477 non-null  str
 38  amortizacionSiguienteId         13477 non-null  str
dtypes: float64(24), int64(6), str(9)
memory usage: 4.1 MB

In [13]:
financiera[["folio", "numero", "pagoFechaEsperada", "pagoFechaRecibido", "pagoMontoEsperado", "pagoMontoRecibido"]].info()

<class 'pandas.DataFrame'>
RangeIndex: 13921 entries, 0 to 13920
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   folio              13921 non-null  int64
 1   numero             13921 non-null  int64
 2   pagoFechaEsperada  13921 non-null  str
 3   pagoFechaRecibido  7986 non-null   str
 4   pagoMontoEsperado  13921 non-null  float64
 5   pagoMontoRecibido  13921 non-null  float64
dtypes: float64(2), int64(2), str(2)
memory usage: 652.7 KB

In [24]:
financiera["montoFijadoPagado"] = financiera["pagoMontoEsperado"]
financiera["montoEsperadoPagado"] = financiera["montoFijadoPagado"] * financiera["pagado"]

financiera

,folio,amortizacionId,numero,concepto,plan,plazos,precio,interes,anticipo,subtotal,...,pagoSiguienteId,vendedorRecibeFolio,sucursalRecibeFolio,vendedorOrigenFolio,sucursalOrigenFolio,liquidado,amortizacionAnteriorId,amortizacionSiguienteId,montoFijadoPagado,montoEsperadoPagado
0,772,anticipo,0,Anticipo,nuevo,26,3999.0,190.0,799.0,6080.0,...,pago-1,33.0,6.0,12.0,14.0,0,NaN,pago-1,799.00,799.00
1,772,pago-1,1,Pago 1 de 26,nuevo,26,3999.0,190.0,799.0,6080.0,...,pago-2,NaN,NaN,NaN,NaN,0,anticipo,pago-2,233.85,0.00
2,772,pago-2,2,Pago 2 de 26,nuevo,26,3999.0,190.0,799.0,6080.0,...,pago-3,NaN,NaN,NaN,NaN,0,pago-1,pago-3,233.85,0.00
3,772,pago-3,3,Pago 3 de 26,nuevo,26,3999.0,190.0,799.0,6080.0,...,pago-4,NaN,NaN,NaN,NaN,0,pago-2,pago-4,233.85,0.00
4,772,pago-4,4,Pago 4 de 26,nuevo,26,3999.0,190.0,799.0,6080.0,...,pago-5,NaN,NaN,NaN,NaN,0,pago-3,pago-5,233.85,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13916,9,pago-14,14,Pago 14 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,pago-15,18.0,11.0,14.0,11.0,0,pago-13,pago-15,302.22,302.22
13917,9,pago-15,15,Pago 15 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,pago-16,14.0,11.0,14.0,11.0,0,pago-14,pago-16,302.22,302.22
13918,9,pago-16,16,Pago 16 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,pago-17,18.0,11.0,14.0,11.0,0,pago-15,pago-17,302.22,302.22
13919,9,pago-17,17,Pago 17 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,pago-18,18.0,11.0,14.0,11.0,0,pago-16,pago-18,302.22,302.22
13920,9,pago-18,18,Pago 18 de 18,nuevo,18,3999.0,170.0,799.0,5440.0,...,NaN,14.0,11.0,14.0,11.0,0,pago-17,NaN,302.26,302.26

In [26]:
avanceVentas = financiera.groupby("folio").agg({
    "pagoMontoEsperado": "sum",
    "pagoMontoRecibido": "sum",
    "montoFijadoPagado": "sum",
    "montoEsperadoPagado": "sum",
    "folio": "count",
    "precio": "first",
    "anticipo": "first",
    "semanal": "first",
    "total": "first",
})

avanceVentas

,pagoMontoEsperado,pagoMontoRecibido,montoFijadoPagado,montoEsperadoPagado,folio,precio,anticipo,semanal,total
folio,,,,,,,,,
9,6239.00,5030.12,6239.00,6239.00,19,3999.0,799.0,302.22,6239.00
14,18146.39,3631.60,18146.39,5185.20,36,10999.0,0.0,518.52,18148.35
17,20349.08,2499.00,20349.08,3009.00,36,10999.0,2499.0,510.00,20349.08
18,14958.30,3130.83,14958.30,4522.31,44,8799.0,0.0,347.87,14958.30
23,5599.00,1759.00,5599.00,2079.00,16,3999.0,799.0,320.00,5599.00
...,...,...,...,...,...,...,...,...,...
764,8999.00,0.00,8999.00,0.00,44,8999.0,0.0,209.28,8999.00
766,14248.50,949.90,14248.50,949.90,16,9499.0,0.0,949.90,14248.50
767,10268.70,749.50,10268.70,749.50,27,6699.0,749.5,366.12,10268.70
769,16148.30,0.00,16148.30,0.00,44,9499.0,0.0,375.54,16148.30
772,6879.00,799.00,6879.00,799.00,27,3999.0,799.0,233.85,6879.00

In [27]:
avanceVentas.to_csv("financiera_fact_avance_ventas.csv")